compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  izzai:
    npmAlwaysAuth: true
    npmAuthToken: '${GITHUB_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.5.3.cjs
